/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.mybash.ui.internal.MybashActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyBashExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MybashActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MybashActivator.getInstance().getInjector(MybashActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYBASH);
	}
	
}
