/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myBash.MyBashPackage;
import org.xtext.example.mydsl.myBash.ParameterProcessor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ParameterProcessorImpl extends MinimalEObjectImpl.Container implements ParameterProcessor
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterProcessorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyBashPackage.Literals.PARAMETER_PROCESSOR;
  }

} //ParameterProcessorImpl
