/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myBash.Assignment;
import org.xtext.example.mydsl.myBash.Expression;
import org.xtext.example.mydsl.myBash.MyBashPackage;
import org.xtext.example.mydsl.myBash.ParameterExpansion;
import org.xtext.example.mydsl.myBash.ParameterProcessor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter Expansion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#getEnd <em>End</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#getRef <em>Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#isHash <em>Hash</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#getIndex <em>Index</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.impl.ParameterExpansionImpl#getReplacer <em>Replacer</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParameterExpansionImpl extends ExpansionImpl implements ParameterExpansion
{
  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final String END_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected String end = END_EDEFAULT;

  /**
   * The cached value of the '{@link #getRef() <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef()
   * @generated
   * @ordered
   */
  protected Assignment ref;

  /**
   * The default value of the '{@link #isHash() <em>Hash</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHash()
   * @generated
   * @ordered
   */
  protected static final boolean HASH_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isHash() <em>Hash</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isHash()
   * @generated
   * @ordered
   */
  protected boolean hash = HASH_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * The cached value of the '{@link #getIndex() <em>Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIndex()
   * @generated
   * @ordered
   */
  protected Expression index;

  /**
   * The cached value of the '{@link #getReplacer() <em>Replacer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReplacer()
   * @generated
   * @ordered
   */
  protected ParameterProcessor replacer;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterExpansionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyBashPackage.Literals.PARAMETER_EXPANSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnd(String newEnd)
  {
    String oldEnd = end;
    end = newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Assignment getRef()
  {
    if (ref != null && ref.eIsProxy())
    {
      InternalEObject oldRef = (InternalEObject)ref;
      ref = (Assignment)eResolveProxy(oldRef);
      if (ref != oldRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyBashPackage.PARAMETER_EXPANSION__REF, oldRef, ref));
      }
    }
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Assignment basicGetRef()
  {
    return ref;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRef(Assignment newRef)
  {
    Assignment oldRef = ref;
    ref = newRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__REF, oldRef, ref));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isHash()
  {
    return hash;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHash(boolean newHash)
  {
    boolean oldHash = hash;
    hash = newHash;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__HASH, oldHash, hash));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getIndex()
  {
    return index;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIndex(Expression newIndex, NotificationChain msgs)
  {
    Expression oldIndex = index;
    index = newIndex;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__INDEX, oldIndex, newIndex);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIndex(Expression newIndex)
  {
    if (newIndex != index)
    {
      NotificationChain msgs = null;
      if (index != null)
        msgs = ((InternalEObject)index).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyBashPackage.PARAMETER_EXPANSION__INDEX, null, msgs);
      if (newIndex != null)
        msgs = ((InternalEObject)newIndex).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyBashPackage.PARAMETER_EXPANSION__INDEX, null, msgs);
      msgs = basicSetIndex(newIndex, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__INDEX, newIndex, newIndex));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ParameterProcessor getReplacer()
  {
    return replacer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetReplacer(ParameterProcessor newReplacer, NotificationChain msgs)
  {
    ParameterProcessor oldReplacer = replacer;
    replacer = newReplacer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__REPLACER, oldReplacer, newReplacer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReplacer(ParameterProcessor newReplacer)
  {
    if (newReplacer != replacer)
    {
      NotificationChain msgs = null;
      if (replacer != null)
        msgs = ((InternalEObject)replacer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyBashPackage.PARAMETER_EXPANSION__REPLACER, null, msgs);
      if (newReplacer != null)
        msgs = ((InternalEObject)newReplacer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyBashPackage.PARAMETER_EXPANSION__REPLACER, null, msgs);
      msgs = basicSetReplacer(newReplacer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyBashPackage.PARAMETER_EXPANSION__REPLACER, newReplacer, newReplacer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyBashPackage.PARAMETER_EXPANSION__INDEX:
        return basicSetIndex(null, msgs);
      case MyBashPackage.PARAMETER_EXPANSION__REPLACER:
        return basicSetReplacer(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyBashPackage.PARAMETER_EXPANSION__END:
        return getEnd();
      case MyBashPackage.PARAMETER_EXPANSION__REF:
        if (resolve) return getRef();
        return basicGetRef();
      case MyBashPackage.PARAMETER_EXPANSION__HASH:
        return isHash();
      case MyBashPackage.PARAMETER_EXPANSION__VALUE:
        return getValue();
      case MyBashPackage.PARAMETER_EXPANSION__INDEX:
        return getIndex();
      case MyBashPackage.PARAMETER_EXPANSION__REPLACER:
        return getReplacer();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyBashPackage.PARAMETER_EXPANSION__END:
        setEnd((String)newValue);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__REF:
        setRef((Assignment)newValue);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__HASH:
        setHash((Boolean)newValue);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__VALUE:
        setValue((String)newValue);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__INDEX:
        setIndex((Expression)newValue);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__REPLACER:
        setReplacer((ParameterProcessor)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyBashPackage.PARAMETER_EXPANSION__END:
        setEnd(END_EDEFAULT);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__REF:
        setRef((Assignment)null);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__HASH:
        setHash(HASH_EDEFAULT);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__INDEX:
        setIndex((Expression)null);
        return;
      case MyBashPackage.PARAMETER_EXPANSION__REPLACER:
        setReplacer((ParameterProcessor)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyBashPackage.PARAMETER_EXPANSION__END:
        return END_EDEFAULT == null ? end != null : !END_EDEFAULT.equals(end);
      case MyBashPackage.PARAMETER_EXPANSION__REF:
        return ref != null;
      case MyBashPackage.PARAMETER_EXPANSION__HASH:
        return hash != HASH_EDEFAULT;
      case MyBashPackage.PARAMETER_EXPANSION__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
      case MyBashPackage.PARAMETER_EXPANSION__INDEX:
        return index != null;
      case MyBashPackage.PARAMETER_EXPANSION__REPLACER:
        return replacer != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (end: ");
    result.append(end);
    result.append(", hash: ");
    result.append(hash);
    result.append(", value: ");
    result.append(value);
    result.append(')');
    return result.toString();
  }

} //ParameterExpansionImpl
