/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myBash.MyBashPackage;
import org.xtext.example.mydsl.myBash.WordElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Word Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class WordElementImpl extends MinimalEObjectImpl.Container implements WordElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WordElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyBashPackage.Literals.WORD_ELEMENT;
  }

} //WordElementImpl
