/**
 * generated by Xtext 2.9.1
 */
package org.xtext.example.mydsl.scoping;

import com.google.common.base.Objects;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.EObjectDescription;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.scoping.IScope;
import org.xtext.example.mydsl.scoping.AbstractMyBashScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyBashScopeProvider extends AbstractMyBashScopeProvider {
  public static class MyIScope implements IScope {
    private IScope scope;
    
    public MyIScope(final IScope scope) {
      this.scope = scope;
    }
    
    @Override
    public Iterable<IEObjectDescription> getAllElements() {
      throw new UnsupportedOperationException("TODO: auto-generated method stub");
    }
    
    @Override
    public Iterable<IEObjectDescription> getElements(final QualifiedName name) {
      throw new UnsupportedOperationException("TODO: auto-generated method stub");
    }
    
    @Override
    public Iterable<IEObjectDescription> getElements(final EObject object) {
      throw new UnsupportedOperationException("TODO: auto-generated method stub");
    }
    
    @Override
    public IEObjectDescription getSingleElement(final QualifiedName name) {
      IEObjectDescription value = this.scope.getSingleElement(name);
      boolean _equals = Objects.equal(value, null);
      if (_equals) {
        return EObjectDescription.create(name, null);
      }
      return value;
    }
    
    @Override
    public IEObjectDescription getSingleElement(final EObject object) {
      throw new UnsupportedOperationException("TODO: auto-generated method stub");
    }
  }
}
