/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.mybash.ui.internal.MybashActivator;

public class MyBashUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MybashActivator.getInstance().getInjector("org.xtext.example.mydsl.MyBash");
	}

}
