/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Case Pattern</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.CasePattern#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.CasePattern#getBody <em>Body</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.CasePattern#getFollow <em>Follow</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getCasePattern()
 * @model
 * @generated
 */
public interface CasePattern extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Pattern)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getCasePattern_Condition()
   * @model containment="true"
   * @generated
   */
  Pattern getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.CasePattern#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Pattern value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getCasePattern_Body()
   * @model containment="true"
   * @generated
   */
  CompoundList getBody();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.CasePattern#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(CompoundList value);

  /**
   * Returns the value of the '<em><b>Follow</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Follow</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Follow</em>' attribute.
   * @see #setFollow(String)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getCasePattern_Follow()
   * @model
   * @generated
   */
  String getFollow();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.CasePattern#getFollow <em>Follow</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Follow</em>' attribute.
   * @see #getFollow()
   * @generated
   */
  void setFollow(String value);

} // CasePattern
