/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Else If Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.ElseIfBlock#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.ElseIfBlock#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getElseIfBlock()
 * @model
 * @generated
 */
public interface ElseIfBlock extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getElseIfBlock_Condition()
   * @model containment="true"
   * @generated
   */
  CompoundList getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.ElseIfBlock#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(CompoundList value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getElseIfBlock_Then()
   * @model containment="true"
   * @generated
   */
  CompoundList getThen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.ElseIfBlock#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(CompoundList value);

} // ElseIfBlock
