/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expansion</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getExpansion()
 * @model
 * @generated
 */
public interface Expansion extends WordElement
{
} // Expansion
