/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Follow Word Op</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getFollowWordOp()
 * @model
 * @generated
 */
public enum FollowWordOp implements Enumerator
{
  /**
   * The '<em><b>Greedy Remove Suffix</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREEDY_REMOVE_SUFFIX_VALUE
   * @generated
   * @ordered
   */
  GREEDY_REMOVE_SUFFIX(0, "GreedyRemoveSuffix", "%%"),

  /**
   * The '<em><b>Remove Suffix</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REMOVE_SUFFIX_VALUE
   * @generated
   * @ordered
   */
  REMOVE_SUFFIX(1, "RemoveSuffix", "%"),

  /**
   * The '<em><b>Greey Remove Prefix</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREEY_REMOVE_PREFIX_VALUE
   * @generated
   * @ordered
   */
  GREEY_REMOVE_PREFIX(2, "GreeyRemovePrefix", "##"),

  /**
   * The '<em><b>Remove Prefix</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REMOVE_PREFIX_VALUE
   * @generated
   * @ordered
   */
  REMOVE_PREFIX(3, "RemovePrefix", "#"),

  /**
   * The '<em><b>Greedy Lowercase</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREEDY_LOWERCASE_VALUE
   * @generated
   * @ordered
   */
  GREEDY_LOWERCASE(4, "GreedyLowercase", ",,"),

  /**
   * The '<em><b>Lowercase</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOWERCASE_VALUE
   * @generated
   * @ordered
   */
  LOWERCASE(5, "Lowercase", ","),

  /**
   * The '<em><b>Greedy Uppercase</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GREEDY_UPPERCASE_VALUE
   * @generated
   * @ordered
   */
  GREEDY_UPPERCASE(6, "GreedyUppercase", "^^"),

  /**
   * The '<em><b>Uppercase</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UPPERCASE_VALUE
   * @generated
   * @ordered
   */
  UPPERCASE(7, "Uppercase", "^"),

  /**
   * The '<em><b>Use Alternate</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USE_ALTERNATE_VALUE
   * @generated
   * @ordered
   */
  USE_ALTERNATE(8, "UseAlternate", ":+"),

  /**
   * The '<em><b>Use Default</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USE_DEFAULT_VALUE
   * @generated
   * @ordered
   */
  USE_DEFAULT(9, "UseDefault", ":-"),

  /**
   * The '<em><b>Assign Default</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ASSIGN_DEFAULT_VALUE
   * @generated
   * @ordered
   */
  ASSIGN_DEFAULT(10, "AssignDefault", ":="),

  /**
   * The '<em><b>Error Default</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERROR_DEFAULT_VALUE
   * @generated
   * @ordered
   */
  ERROR_DEFAULT(11, "ErrorDefault", ":?");

  /**
   * The '<em><b>Greedy Remove Suffix</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Greedy Remove Suffix</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GREEDY_REMOVE_SUFFIX
   * @model name="GreedyRemoveSuffix" literal="%%"
   * @generated
   * @ordered
   */
  public static final int GREEDY_REMOVE_SUFFIX_VALUE = 0;

  /**
   * The '<em><b>Remove Suffix</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Remove Suffix</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REMOVE_SUFFIX
   * @model name="RemoveSuffix" literal="%"
   * @generated
   * @ordered
   */
  public static final int REMOVE_SUFFIX_VALUE = 1;

  /**
   * The '<em><b>Greey Remove Prefix</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Greey Remove Prefix</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GREEY_REMOVE_PREFIX
   * @model name="GreeyRemovePrefix" literal="##"
   * @generated
   * @ordered
   */
  public static final int GREEY_REMOVE_PREFIX_VALUE = 2;

  /**
   * The '<em><b>Remove Prefix</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Remove Prefix</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REMOVE_PREFIX
   * @model name="RemovePrefix" literal="#"
   * @generated
   * @ordered
   */
  public static final int REMOVE_PREFIX_VALUE = 3;

  /**
   * The '<em><b>Greedy Lowercase</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Greedy Lowercase</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GREEDY_LOWERCASE
   * @model name="GreedyLowercase" literal=",,"
   * @generated
   * @ordered
   */
  public static final int GREEDY_LOWERCASE_VALUE = 4;

  /**
   * The '<em><b>Lowercase</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Lowercase</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LOWERCASE
   * @model name="Lowercase" literal=","
   * @generated
   * @ordered
   */
  public static final int LOWERCASE_VALUE = 5;

  /**
   * The '<em><b>Greedy Uppercase</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Greedy Uppercase</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #GREEDY_UPPERCASE
   * @model name="GreedyUppercase" literal="^^"
   * @generated
   * @ordered
   */
  public static final int GREEDY_UPPERCASE_VALUE = 6;

  /**
   * The '<em><b>Uppercase</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Uppercase</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UPPERCASE
   * @model name="Uppercase" literal="^"
   * @generated
   * @ordered
   */
  public static final int UPPERCASE_VALUE = 7;

  /**
   * The '<em><b>Use Alternate</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Use Alternate</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #USE_ALTERNATE
   * @model name="UseAlternate" literal=":+"
   * @generated
   * @ordered
   */
  public static final int USE_ALTERNATE_VALUE = 8;

  /**
   * The '<em><b>Use Default</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Use Default</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #USE_DEFAULT
   * @model name="UseDefault" literal=":-"
   * @generated
   * @ordered
   */
  public static final int USE_DEFAULT_VALUE = 9;

  /**
   * The '<em><b>Assign Default</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Assign Default</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ASSIGN_DEFAULT
   * @model name="AssignDefault" literal=":="
   * @generated
   * @ordered
   */
  public static final int ASSIGN_DEFAULT_VALUE = 10;

  /**
   * The '<em><b>Error Default</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Error Default</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ERROR_DEFAULT
   * @model name="ErrorDefault" literal=":?"
   * @generated
   * @ordered
   */
  public static final int ERROR_DEFAULT_VALUE = 11;

  /**
   * An array of all the '<em><b>Follow Word Op</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final FollowWordOp[] VALUES_ARRAY =
    new FollowWordOp[]
    {
      GREEDY_REMOVE_SUFFIX,
      REMOVE_SUFFIX,
      GREEY_REMOVE_PREFIX,
      REMOVE_PREFIX,
      GREEDY_LOWERCASE,
      LOWERCASE,
      GREEDY_UPPERCASE,
      UPPERCASE,
      USE_ALTERNATE,
      USE_DEFAULT,
      ASSIGN_DEFAULT,
      ERROR_DEFAULT,
    };

  /**
   * A public read-only list of all the '<em><b>Follow Word Op</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<FollowWordOp> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Follow Word Op</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FollowWordOp get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FollowWordOp result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Follow Word Op</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FollowWordOp getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FollowWordOp result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Follow Word Op</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FollowWordOp get(int value)
  {
    switch (value)
    {
      case GREEDY_REMOVE_SUFFIX_VALUE: return GREEDY_REMOVE_SUFFIX;
      case REMOVE_SUFFIX_VALUE: return REMOVE_SUFFIX;
      case GREEY_REMOVE_PREFIX_VALUE: return GREEY_REMOVE_PREFIX;
      case REMOVE_PREFIX_VALUE: return REMOVE_PREFIX;
      case GREEDY_LOWERCASE_VALUE: return GREEDY_LOWERCASE;
      case LOWERCASE_VALUE: return LOWERCASE;
      case GREEDY_UPPERCASE_VALUE: return GREEDY_UPPERCASE;
      case UPPERCASE_VALUE: return UPPERCASE;
      case USE_ALTERNATE_VALUE: return USE_ALTERNATE;
      case USE_DEFAULT_VALUE: return USE_DEFAULT;
      case ASSIGN_DEFAULT_VALUE: return ASSIGN_DEFAULT;
      case ERROR_DEFAULT_VALUE: return ERROR_DEFAULT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private FollowWordOp(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //FollowWordOp
