/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.IfStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.IfStatement#getThen <em>Then</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.IfStatement#getElseIfBlock <em>Else If Block</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.IfStatement#getElse <em>Else</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends ShellCommand
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getIfStatement_Condition()
   * @model containment="true"
   * @generated
   */
  CompoundList getCondition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.IfStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(CompoundList value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Then</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' containment reference.
   * @see #setThen(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getIfStatement_Then()
   * @model containment="true"
   * @generated
   */
  CompoundList getThen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.IfStatement#getThen <em>Then</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' containment reference.
   * @see #getThen()
   * @generated
   */
  void setThen(CompoundList value);

  /**
   * Returns the value of the '<em><b>Else If Block</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myBash.ElseIfBlock}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else If Block</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else If Block</em>' containment reference list.
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getIfStatement_ElseIfBlock()
   * @model containment="true"
   * @generated
   */
  EList<ElseIfBlock> getElseIfBlock();

  /**
   * Returns the value of the '<em><b>Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else</em>' containment reference.
   * @see #setElse(CompoundList)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getIfStatement_Else()
   * @model containment="true"
   * @generated
   */
  CompoundList getElse();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.IfStatement#getElse <em>Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else</em>' containment reference.
   * @see #getElse()
   * @generated
   */
  void setElse(CompoundList value);

} // IfStatement
