/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pipeline Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.PipelineCommand#isNot <em>Not</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.PipelineCommand#getPipeline <em>Pipeline</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getPipelineCommand()
 * @model
 * @generated
 */
public interface PipelineCommand extends CommandUnit
{
  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(boolean)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getPipelineCommand_Not()
   * @model
   * @generated
   */
  boolean isNot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.PipelineCommand#isNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #isNot()
   * @generated
   */
  void setNot(boolean value);

  /**
   * Returns the value of the '<em><b>Pipeline</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pipeline</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pipeline</em>' containment reference.
   * @see #setPipeline(CommandUnit)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getPipelineCommand_Pipeline()
   * @model containment="true"
   * @generated
   */
  CommandUnit getPipeline();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.PipelineCommand#getPipeline <em>Pipeline</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pipeline</em>' containment reference.
   * @see #getPipeline()
   * @generated
   */
  void setPipeline(CommandUnit value);

} // PipelineCommand
