/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.SimpleCommand#getAssignments <em>Assignments</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.SimpleCommand#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.SimpleCommand#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.SimpleCommand#getR <em>R</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSimpleCommand()
 * @model
 * @generated
 */
public interface SimpleCommand extends CommandUnit
{
  /**
   * Returns the value of the '<em><b>Assignments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myBash.Assignment}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignments</em>' containment reference list.
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSimpleCommand_Assignments()
   * @model containment="true"
   * @generated
   */
  EList<Assignment> getAssignments();

  /**
   * Returns the value of the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Command</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' containment reference.
   * @see #setCommand(Word)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSimpleCommand_Command()
   * @model containment="true"
   * @generated
   */
  Word getCommand();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.SimpleCommand#getCommand <em>Command</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' containment reference.
   * @see #getCommand()
   * @generated
   */
  void setCommand(Word value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSimpleCommand_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getParameters();

  /**
   * Returns the value of the '<em><b>R</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myBash.Redirection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>R</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>R</em>' containment reference list.
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSimpleCommand_R()
   * @model containment="true"
   * @generated
   */
  EList<Redirection> getR();

} // SimpleCommand
