/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myBash;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Processor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myBash.SingleProcessor#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myBash.SingleProcessor#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSingleProcessor()
 * @model
 * @generated
 */
public interface SingleProcessor extends ParameterProcessor
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myBash.FollowWordOp}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Op</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see org.xtext.example.mydsl.myBash.FollowWordOp
   * @see #setOp(FollowWordOp)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSingleProcessor_Op()
   * @model
   * @generated
   */
  FollowWordOp getOp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.SingleProcessor#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see org.xtext.example.mydsl.myBash.FollowWordOp
   * @see #getOp()
   * @generated
   */
  void setOp(FollowWordOp value);

  /**
   * Returns the value of the '<em><b>Word</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Word</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' containment reference.
   * @see #setWord(Word)
   * @see org.xtext.example.mydsl.myBash.MyBashPackage#getSingleProcessor_Word()
   * @model containment="true"
   * @generated
   */
  Word getWord();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myBash.SingleProcessor#getWord <em>Word</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' containment reference.
   * @see #getWord()
   * @generated
   */
  void setWord(Word value);

} // SingleProcessor
