/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalMyBashParser;
import org.xtext.example.mydsl.services.MyBashGrammarAccess;

public class MyBashParser extends AbstractAntlrParser {

	@Inject
	private MyBashGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_SL_COMMENT", "RULE_C_LINE", "RULE_WS", "RULE_HIDEN_NEW_LINE");
	}
	

	@Override
	protected InternalMyBashParser createParser(XtextTokenStream stream) {
		return new InternalMyBashParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Bash";
	}

	public MyBashGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyBashGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
